apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - rbac/kube-state-metrics-clusterrole.yml
  - rbac/kube-state-metrics-clusterrolebinding.yml
  - rbac/kube-state-metrics-serviceaccount.yml
  - rbac/prometheus-clusterrole.yml
  - rbac/prometheus-clusterrolebinding.yml
  - rbac/prometheus-serviceaccount.yml
  - pvc/prometheus-data.yml
  - configmaps/grafana-dashboard-provider.yml
  - configmaps/grafana-dashboards.yml
  - configmaps/grafana-datasource.yml
  - configmaps/grafana-alerting.yml
  - configmaps/prometheus-config.yml
  - deployments/grafana.yml
  - deployments/jaeger.yml
  - deployments/kube-state-metrics.yml
  - deployments/prometheus.yml
  - daemonsets/node-exporter.yml
  - services/grafana.yml
  - services/jaeger.yml
  - services/kube-state-metrics.yml
  - services/node-exporter.yml
  - services/prometheus.yml
  - ingress.yml
