---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eval-rabbitmq
  namespace: ai-services-qa
spec:
  encryptedData:
    url: AgAP8adFr5oGhHBNh9dMFRZ0vuJXjgxkBl69kbfivNClKLAqYtRZHFttek0i/RDNawmxRFo3g5SioZ0UNE8PV/dBFHKoX4JAPF11+iGKta98GaNW6WIJciU/hIswTWnvBMthVCMRgeAwDMQdoWlN+4WGa/1p4CcG7xWkN3vEIKlo/WYFhFfGYIkCokErrisuf+52KpMwnHwZEntvBgqOdc5k57PmiKnToPbNjm8spWRYAMuCF65HIjHDzDgloKEyhSJgqm17HR/rfXXU9FV8oRyohtrhaoZEA80uY+/8R+HKPTUJXtHjJ+jk4eun/P6vWeQPlf5oA9ajm4is9USuvWACNtrJP/KMTfi+6/vwRp7wcO62RsK+TB5YvxFk1ClQKqNTBVuFXPUnHxhsNnnav4IP1EdCrRJ8sSYi4KEoF9DpYPrnw8bsU3zIJxWqfhPrBVoFTZDMqRv18YrgUaCVhQi9MPcw0QVgnqOOK/vsJsY+u9x+rCoDgNjH/unesi4Z2n9aLLAr31QCLRN5Ded6RAOszJAl2nJKF1KF+eZxLSYEakfknZTI2KEFMK0YAZfzqc88D8CpGXZp5Hs22PY1ra4N8RmUGkt5J7u0rUbPtEki9KZhdGfCPEc7bGZwphkggh1WEwzyx6RO4+SdfXtqQzfukGE+B/RdQLrkekOIFNjPc8O2kR/xs+cPSjEG/JoWPvkcxhaCgtyVxJsgv9xJ5lFrKlgFlowJadPkc9haMZqevlqrwDRWNVRSoIoxFlr5iW0ZCKnsU24sbuY2oakeZr//
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: eval-rabbitmq
      namespace: ai-services-qa
    type: Opaque
