apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-backup-readonly-pv
  labels:
    type: backup-readonly
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-readonly
  hostPath:
    path: /backups/postgres
    type: Directory
  claimRef:
    namespace: java-tasks
    name: postgres-backup-readonly
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-readonly
  namespace: java-tasks
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: manual-readonly
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: backup-readonly
