---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cart-service-mq
  namespace: go-ecommerce-qa
spec:
  encryptedData:
    MQ_PASSWORD: AgCBmg0w83h0aDMEbz7vyLkVKgEc7lXfdvpdXDQ3BhHPQSpXamv/+HKoZQ42AucrRfEPsDTsdkgxF1FteBm6PrQVHhHKKy2TLF6aamQgA+hzORExquDrJc6WzFWKUMruC1B9BSWLruD6DjgtvldWy7++3oZet1CeW0VuPvpXCUGBDWXoabrXpL9oVKUFH32VNF2mxL03Z3J20Ek29YIk0wJqlBZN2U9+2AaWSayotmfM538/VOrUxff7Kg+uDYAGX9B/7QSngC9+lXi3BxkGDFPOeDlBAki9HPA8fpvZ+Qhcmb6HyyjxPC0vcbtzRi7vAY8qJTbh4Uzyuyow4PQElZl73F+JO3KdSwD5Ys+bF5HQOu4BS2C7nO93nursmnXPm7N5fiAlmaywdkgBa8f60rwF9aiP+zzZ8vmRXaGG9aeH9rwRu+yPzqEiv80Q+cuFCOXt+w/HXI8P3tzD2I/OuVVhEPK2ZMjtaapJ8sdKUsJuUc8R5wh2imBZWI+bpn0uX44F7egPzNpn0z9lEtpqr+zojidXzZs22e31MZqpofpCXA9DegZvteIf9+Es+RBh+4kvZmYwMJuH6hsaRqQhaVH9eP60hZkxwKGFj+Ddm1yrIn/saBXSzCYNmfU9+qtjbhtfGLCqV2a1jFS/n5lCicFuN7oSUBBhAMyTi5zbm4FG7F6xeKpo3HdZUTg+bksJfikFiaeZGg==
    MQ_USER: AgDFUvwpA2oY/czzEDbfAi8NyQ1qooh1sMc9eS9+tMa9A4wbvKKKts+vD7KrhYS7kUN11oLAS50U+UGAmu85iOzFZPVXXbpZZqOzrsL9m3grt7l6sN/Ih+Dky34rVeGJNBSwMvzdIWjRJTonSJPfOryPtVGD8Z8y2TZUTKQW0ITLgFFfXhbluhVcw5PTQGMimYzL3SbBfMqWdneV6vw2+5eVC3ru56j1ZTqD1cQ/Qi1poAP6xQYh2iRStjIxwWl6W3YAEi2TJ8QCX/saaVtQmyZnHRaw4OtSnL41d+uERX/7rO0om+oH6WA68Gj7uhlPowVMICkuNreKWDE68gV7865gq0EMTnv0P6gwncQvIj+jheE7UYhdnbZiOCId+ZN/EfkzafC9ZTWS/X/ywsIlqKGrOUtsmwrE170AY7tRfuw7S+uosrDVie8uDN6SPkAPy7chSvrhCbuH4iLUEPGakDq0F8Usa4129NdM4uFMMa8na4Vh0j47RMv1x9z5vvhtpFJ21g433s3q0Mms1I6h7R3IUqM0a5ORKXt++bRpiMql8Ay1e0YbcuviKxvWJBatIwlTES6ZDWH6Jq9q2LG93MjHF2XY342cntt2u0tmD3tAW7UCEJbgNX8i5ON9mGo37ltI5JxeSNiAVK7R+6g7wBV/91eKLyUgdrM5liPdWKpH/RxDJINUZm+meqPbkFcoNC8dgZilog==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cart-service-mq
      namespace: go-ecommerce-qa
    type: Opaque
