---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cart-service-db
  namespace: go-ecommerce-qa
spec:
  encryptedData:
    DB_PASSWORD: AgBB3kIG9PzvupXXKT/RCUVf8bbm4O9hk07SYEFSTixT6Rrg3CIiNurPPgo4pLxKTIubGeYuR2OjzNDkC9JFNLYDem9i/PVngGJJZmV86nij0HD0TsYe6YvaQ4ZiCuvI2mKvIZI4ThkAMOFg6qJzlBl/2EH8bOWvmxYFW2RHgeT3A2UHebeE7ZUZvGzRTeJ8WqkekUkSwKnvkYODFzFGct+VdZLzJKctuDsiYp1+pMEw/djrtZCJnLauhc/oazoXWGxsaqqGK0YiFZSSDGgqO6wQ0PkUSSEJSvjNbRy3C/aAn7w+zd0fVjsTZd33CbuJcnoaCuU1X0XOVZuUn7TelGeS8uDfr4ThgBWURO5/5J/Fj+BqyAsekcFmRBA7sG7bo0uGYLLZrHIzVCTwHwMuxRN7Bn3Q808iQw0QPy4GcD6FC8k/ct210VMafwlYLnsNAPIbFg6uhsLdIXhiwNYVzFdRIZPRZr64aEZdsxtzvb8DtloG08ysj9SPX3mHttjDujVzqkEcct9nL+VvrwVYxgEr2rKE81kGXbLbTMH5LbQMoXXl/MDGj3g5cWjU1awFHMjKaKP/Iyh0HNARYcweGqz24FAZFkErJyOVAE1GTmS69smZUBsvSXcsbeIyUTioGuKpeasQLDuJXPP1JzQj/N4Be27BMWhlYppwl7VMwFHwnxVD0uNXinjdIbwPm19wStDRc+LA3zCKhg==
    DB_USER: AgBZyv+S7nD1x6RYV3qO4gUoYr7pP3rQrP7fTw4EZeE6hXbDQOxhwogMVOKahI/KF+0nUROZSRC11RZtrNC7UAVBXLz/+QvqgGIFre4FWl+5kuRjmnqGQdtm1QBlat4HbeEMf0sBju4YOyPDllDWefmIN5+U1vBqbqCeF8JeElb8bYGzBBNZy84KLsT6+BY5wXyVb/DxsvC8Zl8iVNa2WVHmipLOg6eh0x5/hXCiS0zXP4xAtnL0YWk4b5BRDtemJsdvqf+PJdf2IvgqtbrIVuHcmgTmzs26hg/qwhbMmbtPynfk4tJApJwjYpTBK/31Y6s9oJPC8/1wn+XoVB4ah07lJVI0x8W8Ix+gDHXMMNsSQym0hl3ME8UG6H9GDwmT1d458X04kA4CsvrBVGy653PBoVli5mknHtmUgiYI8AWLqjNPviVix2qHdekcoPAEYHJtq8Bf7Fpkil4ukk2SvGxNgZE+9dwsmem7QWYidIBX1b0W8NzoD2tRsExlV2ZJs5gGvUB6ae9bY0YJcO0BiWtEp4tmeqIylUdQp43Ci1PNAiAraucccXaj5BFu7w0FEGjS5taOFVTJ5GWSiEeuv4pQ7R0EUnu6Wyvn4ii4DLbDm+k++3a48Os+EnJKWuFBCLFnSnp6eX45IKncyW0G1/nxw80aGfiA6FIQmTeAp95KjA8uVkSy6RVEVsXe1nPHu3Pz8qEegnSyYg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cart-service-db
      namespace: go-ecommerce-qa
    type: Opaque
