apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-ecommerce-qa

resources:
  - order-projector-db.sealed.yml
  - cart-service-db.sealed.yml
  - cart-service-mq.sealed.yml
