---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: order-projector-db
  namespace: go-ecommerce-qa
spec:
  encryptedData:
    DB_PASSWORD: AgC6TAEJNItxeRl/GH/ZYJhYT7jTrMEocj4I0OzjbnMJrHEcN/Lj0EFeWLkmCBS9A3y6LILRIIv/Cp+wG+2URiU2XOBBaiG8LYuphopatKTzAQuTZZGGVEFWrJ6FNrAxHhD3MWs8e7fvVBiZCBM7zVqA1uxjggtMj4KR3Nqdcxh8Qu+mpLb/5Z4RRnvva9dyP9h1y12H1fQnBQI4dZb1cGy6NNJ+ketJkhXy6x9+GitNuu+QwHEjtwRABzDNWkGQECCUcjX2cJpl5Iqkv9oENFrrgXOpYEUbwJFv3iMkVbz+zrK8E9nZ2J/96y4pH/p0X8OenBmBjRwfO57tSYmON9PMShm+UvfhucCIGXe1o5NMbPBrMoKVj62vM8DUZuKEYMNpaJnRhH4lzebrsSAkEkDK/I81KOfzprzLD2qOU+6yHjSk/SV9WJvgeso5Jyi8tLfiknsLrrfQquB1Oc5zQG2YG/Xp/FpewddleVglxe0TNyMZBrLLtDdjnTyczInxfY3jp7hY3dVo6fZAv2JvtkD2CPNj1Kbm3TwKa1eBFbdPHoCB3XwGe9rOCsP0Kzg93Vb5FKEPzapPW/3A4BjOzq9w0nmiV26xuUOzncz4sHEzGd7BY3zIDQR6+jF56BfVd7HlmORCEBVRHRKEuw3dSzyAHv0iVNLRMMpM7F/WnYsQHHZGVuZH49SbNb3rBZlKEKjvItgV28cUtw==
    DB_USER: AgAF+qMDzEJyDlo27f7JnekzV1iqy7HH+lgMYECF7Gb6Q28iS+2ERHpozpZQ95z07GGkZ2TRrUaERv8hFn4DCm1XiMKpUwcpl8qZfxmbwS2MqeqWbY30HbXj7aEjIQbqctla38l+jCs+BBT7pjFFryXih45ysgiUegWX8yTEJk0ESpeYXs089Psx2Fw9OppXca0Xey4j9zqTJB7SZ8weCVqc1k2TZ0llBFswqmoGPZvXhTVQ77gAyQJtKbzEQSMrW2wGOVW9blXf5BETVJU21HtGBqMhh18Dp2T8eZBmQ37Lv1aa1BBT4+0kChm+4TrnDTcMYoJ0qFVPd54OLE7Dzo6RapJSVEDOrly8mizsnQfnxvP2u3pZMQgQ+zfBiPFs3yA1OD+XpuP8NMxXXqljBJYzQJ0YAWXqNXolXO1GokaaxAwRtIgZJIb2sHPHrtR+GVzYjYzVcCA7rhJddqQ2595ziL6QsXkUyXcJGevfe16oOjHUx6GW2eWk1lbz6Pfk/hAwYVl0gZLINPeuem4qNJUoiqo+csz7Oq8I4zeN752ANiwTz4M+86vAVgL0drFdlE+yE80fZdiE2skFG+DsbZWre1qn3KkB7t0jtJe9naOMoqAau+8DBuoUrzCpoKEBP/o1q3dRkC125I2GkZ9/PGe6VS9/MsKwccuSAtTIWyq1r8OvEffOho6HFL2ZqTTRa0A9PgsS/pen+A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: order-projector-db
      namespace: go-ecommerce-qa
    type: Opaque
