apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmaps/ai-service-config.yml
  - configmaps/auth-service-config.yml
  - configmaps/order-service-config.yml
  - configmaps/analytics-service-config.yml
  - configmaps/product-service-config.yml
  - configmaps/cart-service-config.yml
  - configmaps/payment-service-config.yml
  - configmaps/order-projector-config.yml
  - deployments/ai-service.yml
  - deployments/auth-service.yml
  - deployments/order-service.yml
  - deployments/analytics-service.yml
  - deployments/product-service.yml
  - deployments/cart-service.yml
  - deployments/payment-service.yml
  - deployments/order-projector.yml
  - statefulsets/kafka.yml
  - hpa/auth-hpa.yml
  - hpa/order-hpa.yml
  - hpa/product-hpa.yml
  - hpa/cart-hpa.yml
  - jobs/auth-service-migrate.yml
  - jobs/order-service-migrate.yml
  - jobs/product-service-migrate.yml
  - jobs/cart-service-migrate.yml
  - jobs/payment-service-migrate.yml
  - jobs/order-projector-migrate.yml
  - services/ai-service.yml
  - services/auth-service.yml
  - services/order-service.yml
  - services/kafka.yml
  - services/analytics-service.yml
  - services/product-service.yml
  - services/cart-service.yml
  - services/payment-service-svc.yml
  - services/order-projector.yml
  - pdb/auth-pdb.yml
  - pdb/order-pdb.yml
  - pdb/ai-pdb.yml
  - pdb/analytics-pdb.yml
  - pdb/product-pdb.yml
  - pdb/cart-pdb.yml
  - pdb/payment-service-pdb.yml
  - ingress.yml
  - network-policy.yml
