apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmaps/ai-service-config.yml
  - configmaps/auth-service-config.yml
  - configmaps/ecommerce-service-config.yml
  - deployments/ai-service.yml
  - deployments/auth-service.yml
  - deployments/ecommerce-service.yml
  - hpa/auth-hpa.yml
  - hpa/ecommerce-hpa.yml
  - jobs/auth-service-migrate.yml
  - jobs/ecommerce-service-migrate.yml
  - services/ai-service.yml
  - services/auth-service.yml
  - services/ecommerce-service.yml
  - pdb/auth-pdb.yml
  - pdb/ecommerce-pdb.yml
  - pdb/ai-pdb.yml
  - ingress.yml
  - network-policy.yml
