apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-config
  namespace: java-tasks
data:
  POSTGRES_HOST: postgres
  POSTGRES_USER: taskuser
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  REDIS_HOST: redis
  ALLOWED_ORIGINS: http://localhost:3000,https://kylebradshaw.dev
  COOKIE_DOMAIN: ".kylebradshaw.dev"
  COOKIE_SECURE: "true"
  COOKIE_SAMESITE: "none"
