apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: go-ecommerce
data:
  DATABASE_URL: postgres://taskuser:taskpass@postgres.java-tasks.svc.cluster.local:5432/ecommercedb?sslmode=disable
  ALLOWED_ORIGINS: http://localhost:3000,https://kylebradshaw.dev
  PORT: "8091"
  OTEL_EXPORTER_OTLP_ENDPOINT: "jaeger.monitoring.svc.cluster.local:4317"
  COOKIE_DOMAIN: ".kylebradshaw.dev"
  COOKIE_SECURE: "true"
  COOKIE_SAMESITE: "none"
  GRPC_PORT: "9091"
  REDIS_URL: redis://redis.java-tasks.svc.cluster.local:6379
  TLS_CERT_DIR: /etc/tls
