apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: go-ecommerce
data:
  DATABASE_URL: postgres://taskuser:taskpass@postgres.java-tasks.svc.cluster.local:5432/ecommercedb?sslmode=disable
  REDIS_URL: redis://redis.java-tasks.svc.cluster.local:6379
  RABBITMQ_URL: amqp://guest:guest@rabbitmq.java-tasks.svc.cluster.local:5672
  ALLOWED_ORIGINS: http://localhost:3000,https://kylebradshaw.dev
  PORT: "8092"
  KAFKA_BROKERS: "kafka.go-ecommerce.svc.cluster.local:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "jaeger.monitoring.svc.cluster.local:4317"
  PRODUCT_GRPC_ADDR: "go-product-service.go-ecommerce.svc.cluster.local:9095"
  CART_GRPC_ADDR: "go-cart-service.go-ecommerce.svc.cluster.local:9096"
  PAYMENT_GRPC_ADDR: "go-payment-service.go-ecommerce.svc.cluster.local:9098"
  AUTH_GRPC_URL: go-auth-service.go-ecommerce.svc.cluster.local:9091
  TLS_CERT_DIR: /etc/tls
