apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: go-ecommerce
data:
  DATABASE_URL: "postgres://taskuser:taskpass@postgres.java-tasks.svc.cluster.local:5432/paymentdb?sslmode=disable&application_name=payment-service"
  DATABASE_URL_DIRECT: "postgres://taskuser:taskpass@postgres.java-tasks.svc.cluster.local:5432/paymentdb?sslmode=disable&application_name=payment-service-migrate"
  PORT: "8098"
  GRPC_PORT: "9098"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.java-tasks.svc.cluster.local:5672"
  KAFKA_BROKERS: "kafka.go-ecommerce.svc.cluster.local:9092"
  ALLOWED_ORIGINS: "https://kylebradshaw.dev,http://localhost:3000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "jaeger.monitoring.svc.cluster.local:4317"
  TLS_CERT_DIR: "/etc/tls"
