apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: go-ecommerce
data:
  DATABASE_URL: postgres://taskuser:taskpass@postgres.java-tasks.svc.cluster.local:5432/productdb?sslmode=disable
  REDIS_URL: redis://redis.java-tasks.svc.cluster.local:6379
  ALLOWED_ORIGINS: http://localhost:3000,https://kylebradshaw.dev
  PORT: "8095"
  GRPC_PORT: "9095"
  OTEL_EXPORTER_OTLP_ENDPOINT: "jaeger.monitoring.svc.cluster.local:4317"
