// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cart/v1/cart.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CartItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{3}
}

func (x *ClearCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ClearCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartResponse) Reset() {
	*x = ClearCartResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResponse) ProtoMessage() {}

func (x *ClearCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResponse.ProtoReflect.Descriptor instead.
func (*ClearCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{4}
}

type ReserveItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsRequest) Reset() {
	*x = ReserveItemsRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsRequest) ProtoMessage() {}

func (x *ReserveItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsRequest.ProtoReflect.Descriptor instead.
func (*ReserveItemsRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReserveItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemsResponse) Reset() {
	*x = ReserveItemsResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemsResponse) ProtoMessage() {}

func (x *ReserveItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemsResponse.ProtoReflect.Descriptor instead.
func (*ReserveItemsResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveItemsResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseItemsRequest) Reset() {
	*x = ReleaseItemsRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseItemsRequest) ProtoMessage() {}

func (x *ReleaseItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseItemsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseItemsRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReleaseItemsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReleaseItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseItemsResponse) Reset() {
	*x = ReleaseItemsResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseItemsResponse) ProtoMessage() {}

func (x *ReleaseItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseItemsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseItemsResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_cart_v1_cart_proto protoreflect.FileDescriptor

const file_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x12cart/v1/cart.proto\x12\acart.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x01\n" +
	"\bCartItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x0fGetCartResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.cart.v1.CartItemR\x05items\"+\n" +
	"\x10ClearCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x13\n" +
	"\x11ClearCartResponse\"I\n" +
	"\x13ReserveItemsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"Y\n" +
	"\x14ReserveItemsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.cart.v1.CartItemR\x05items\"I\n" +
	"\x13ReleaseItemsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"0\n" +
	"\x14ReleaseItemsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa9\x02\n" +
	"\vCartService\x12<\n" +
	"\aGetCart\x12\x17.cart.v1.GetCartRequest\x1a\x18.cart.v1.GetCartResponse\x12B\n" +
	"\tClearCart\x12\x19.cart.v1.ClearCartRequest\x1a\x1a.cart.v1.ClearCartResponse\x12K\n" +
	"\fReserveItems\x12\x1c.cart.v1.ReserveItemsRequest\x1a\x1d.cart.v1.ReserveItemsResponse\x12K\n" +
	"\fReleaseItems\x12\x1c.cart.v1.ReleaseItemsRequest\x1a\x1d.cart.v1.ReleaseItemsResponseB=Z;github.com/kabradshaw1/portfolio/go/cart-service/pb/cart/v1b\x06proto3"

var (
	file_cart_v1_cart_proto_rawDescOnce sync.Once
	file_cart_v1_cart_proto_rawDescData []byte
)

func file_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_v1_cart_proto_rawDesc), len(file_cart_v1_cart_proto_rawDesc)))
	})
	return file_cart_v1_cart_proto_rawDescData
}

var file_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cart_v1_cart_proto_goTypes = []any{
	(*CartItem)(nil),              // 0: cart.v1.CartItem
	(*GetCartRequest)(nil),        // 1: cart.v1.GetCartRequest
	(*GetCartResponse)(nil),       // 2: cart.v1.GetCartResponse
	(*ClearCartRequest)(nil),      // 3: cart.v1.ClearCartRequest
	(*ClearCartResponse)(nil),     // 4: cart.v1.ClearCartResponse
	(*ReserveItemsRequest)(nil),   // 5: cart.v1.ReserveItemsRequest
	(*ReserveItemsResponse)(nil),  // 6: cart.v1.ReserveItemsResponse
	(*ReleaseItemsRequest)(nil),   // 7: cart.v1.ReleaseItemsRequest
	(*ReleaseItemsResponse)(nil),  // 8: cart.v1.ReleaseItemsResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_cart_v1_cart_proto_depIdxs = []int32{
	9, // 0: cart.v1.CartItem.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: cart.v1.GetCartResponse.items:type_name -> cart.v1.CartItem
	0, // 2: cart.v1.ReserveItemsResponse.items:type_name -> cart.v1.CartItem
	1, // 3: cart.v1.CartService.GetCart:input_type -> cart.v1.GetCartRequest
	3, // 4: cart.v1.CartService.ClearCart:input_type -> cart.v1.ClearCartRequest
	5, // 5: cart.v1.CartService.ReserveItems:input_type -> cart.v1.ReserveItemsRequest
	7, // 6: cart.v1.CartService.ReleaseItems:input_type -> cart.v1.ReleaseItemsRequest
	2, // 7: cart.v1.CartService.GetCart:output_type -> cart.v1.GetCartResponse
	4, // 8: cart.v1.CartService.ClearCart:output_type -> cart.v1.ClearCartResponse
	6, // 9: cart.v1.CartService.ReserveItems:output_type -> cart.v1.ReserveItemsResponse
	8, // 10: cart.v1.CartService.ReleaseItems:output_type -> cart.v1.ReleaseItemsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cart_v1_cart_proto_init() }
func file_cart_v1_cart_proto_init() {
	if File_cart_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_v1_cart_proto_rawDesc), len(file_cart_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_cart_v1_cart_proto_depIdxs,
		MessageInfos:      file_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_cart_v1_cart_proto = out.File
	file_cart_v1_cart_proto_goTypes = nil
	file_cart_v1_cart_proto_depIdxs = nil
}
