---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cart-service-db
  namespace: go-ecommerce
spec:
  encryptedData:
    DB_PASSWORD: AgCV4ZRqjIMb5ZE6q3bbwm65vS7yzpZeGFuuRhwaiywNrFsXPl12E5S2TiSEHFH80wI9KrBmQ2yya2ZQw+ommZrdbdDr0RHlg2s6wJMinQHPDhSh4OFkVPPhH/n+ghTVMhHKS5LdpxQfxSjnv42v90ctpRiD9HmBHuif4YpS+8F2FnxLrg8XuYx3Xq7ZlAllmwwPe43Dd4pdMWwdpr06ArfZvD2Vjxybd8pDJNYp30Lo37sEqdxARE6CQJP+1OiWSiMw+1ly23WQ+qc4lbb08iOUoYEWVsF5AgEC357coc1kNU/BivsplWkQQ8OjtRvnhXowMkuRGGRwA7GOrrAAt8hDQE1jWrLVGbWJVLhWAR/Dcqfb8sZmCN92A+IFWRziN03G7DZDMCjl1hh0lINoL32NHkHKZ6VZFvAGINurf3bl8+Mu9jJqEvr5cfccQtqfPN1tVUstkrWdyTKXoKbjA8C4WNyQskUfqYpBjEySNcDN8snfu20neX5amAG1TiOiufqXmp+DSfrs1Qi8sPI8g1J6lqdS+y9b57dsGZKTlQ5H62ChBqjpLQP6GEEBmWN0GAckBonGgXR7rMokIzHrL4IjU4lH5XG09xn/EAt/ZT6AVwS6BwrSLy1BWQEe83A6lMQQ5beCiJhNeaXpRKkF6Eb1Rc+4LTH+/cZbgg97uv3VtrNVMKVv0xQzPu/5GCNAPXzHaramCF+BaQ==
    DB_USER: AgBGRfNh7bxYHpKx5dOu9avntO+yeXsV74jAlZ2jmseovBpqOGTvJtshBLmV4wpoNScztWoo/pGpQQrsa6nPHvqcuEVzp7o+XWlpWuGU8RK1tirWwhjnqL/Pk4zDAxuOh12z7oi1wPBX3BKV2X9npjfwBBJUgVh9rTWoYtka67Zhz12Wqk94CIzbnqroXW43jdM3i0YhcNrOKZGVTB7DFgpG7a4LSKOcYrrNhCKxDpMIAzdhs1hZ8m1zraopbQhXerFMqAYxLWVhtjpyWodmd9hWPqUgy8YoIAixdvHGWCaTBjthYamWL4pZ2a1ejgSkPZFuWRHbjnC5RzHvp3EEWR0uxups/ApzjOHiYv2K5CqUatKgaqckojJHVY7+0OSUBxQ/7/0GgM6Y/U1jJ/+EY4XYCVEA5z3q4aLtT224ftokYMgL1v/rjY9j5sRByzvU+B5bn/GimYjInTB0awAA4OlGCG51oy3v4bbTeLFNSu5CVRlL9mZpZDdXokynqkeNs09AUJG3mRgHH4gAjqaeDFOt6WVI5VvHWazB3XTXWl/tKvFj2J5LweQ0XmzjQpOsAyYQjZrbb2Fy1qDeU3tanIr49HoeBCF32AzS/Qky0K+DXdHl4x+ZBRIY+xYRKEXKpEWjCukHdowoxTL/P8QxCixUdaR5fGzIto1rWisQMQc4EBsylsuL90zLBaKhYtHTIKIQvjZIUDnftA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cart-service-db
      namespace: go-ecommerce
    type: Opaque
