---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cart-service-mq
  namespace: go-ecommerce
spec:
  encryptedData:
    MQ_PASSWORD: AgBi8EZ9jP1/C9fgqXOJUL8TfNM63uqiCuLeU4CTpWNofCs3ehINs5EBBWLuucsLuXuYyDRHE2vPtbkJ85e9XtuzVh90AnGrkpkc/zb248ZO14HJ35bnUU2WBHP/qSDP95be8Nh3Gar8rqrsqAt4qI0C2YTlurdlWJKAbkcsoZh8PrKFLyv0N8C9eNIn85YQssyJPky/m06E1kK3ZqCR0v2QpN9YuY5oJy5veHMWzu/TngB5FMvJBNKyLYc33a+sUEfVbLEvE5HE3VUJxrXxl8jGzq2L4xGeUrW6ZEojnVgwOooaNJlaTfjDgyXvByiDFIVBHxH1N8Me7GH51jlnW7jF6QdKAB38qfPINuuWCtCGuam/oK5KS4P3x/9qImOvp7gT/cwULg1xDDYXQYQDnL6riaMC9XHaUmwbZ8fOABIUknU69haPioQBMfej/NL8yXNyjckoUiq8Mbswgoy0D72O7PaNAJfThinZ1QnABtZQ/no27mSErGhO3RjVYkbRXQrFocsyFKsldfKuHetTQZmWNiXOtaZ12YUBGUqTu5KivcwqkO1xWx8DGuc0Sn8L0QHZ7UIxbHe/NJ2G4TGONy20Hthh9SV9VmpQ1u0z/yOK9BFj9tFEgi4E6+cMMWeP9Ml8/AE4Ys3Nay6W9c+j7jyaUGcCzaGCYGW6eSQ18CVU5ZUfDSAS4zPodH6iAZeqHQAwVG26+w==
    MQ_USER: AgBxGpuTpBMGMufcGsppPO1FlHK7/6ZxAl75BSx6eLaAr97r57EjbJsJ6gL90uIz4wNPdyUZwhcbUYvechdUuu63MrPoMG6P2Fl0Y1mGD+SXWckVwlfT9ZyQeRpFZvhAlcneWpKzW9CBHbZpIqB1bZ+oztej2l5C8IoU+rT0M4rJ3mm1YC54NmOHhkY8WmIGMV9BEMAPYuuMg5/qycfs/tTbuqMPmHH481LovDe0yBGiwcx9FIUCBTbKCk0RrJEVMEv7iUEsazA+EGVvxcyWbgrlK+4SVdecSle5C6gXw5jJgBkQVFJDVFAKJzffseky3ha+Dp0uU2vUwLye7iUlV6Wm8mRUpAgcEJyQpHYX4etXjW6Z6ckZwouzk0KsCXX3RHqGf+wgU6fUDgmYqM4WAol5k3lBfqpFmo2NEQ0Z7CVFeTzL0eoJbGog1YlF87BiZ+owNFmTx8Kn/daY24LdPwWGsoMWwmwlZMHFhamR2TB2rNGNaVzEQUvzNF11A5+u2IBiRvpxhKHujWQWden7RnDCG3rWoWWbvc8spGWXeg7DrOk/uSHRH3qUbRlPcZ9oocslL1791vuaJqOs+/QmL2Vj9Ypj0zx2En2EjI0gAKV75Wk1bQnH1828sDhaAqF3m6B2zIy5Q+fdQjoeN68PD+zy2mSS2GJLKsGXbtJmNhIIO5HofLuUTXEI3namrBBMfiqbVX9q2w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cart-service-mq
      namespace: go-ecommerce
    type: Opaque
