apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-ecommerce

resources:
  - go-secrets.sealed.yml
  - stripe-secrets.sealed.yml
  - order-projector-db.sealed.yml
  - cart-service-db.sealed.yml
  - cart-service-mq.sealed.yml
