---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: order-projector-db
  namespace: go-ecommerce
spec:
  encryptedData:
    DB_PASSWORD: AgAxCSXjbaqjC7WT5sZ37U1PpBkGsNJG9u6Gx1zzgS8Z0YdNHRNV2R8bVrnR7y8EV+d4jZMD9YjpEcP8Y9DJTs6kXMtD55U9VJdS3gtDoMwiM9VTlgDdo7UiDT7JA4r/xWgS0iLp8FeXLdciUPjNqe/NY5WZO9EwUhikbMC5v7sAier9myvzCVWRPxQCkW9Nsk8Qw9+CxfyRihYVGS1pOXJeeJZZrBTMwqFRZq2YFceSeTdeM/5Bex4Zz/8rkJVCPeZdSdyI3P/O2EQKIvqq8FMNcJ1O53dzkZ2gC/GllOQ4nlVI609rYmILNq2vUt1rG6mUqICUkxRikNqTYRBs8IDnrDQ707b78nBsVcFPNxD0j+M5jws4fY8d6oMQw7CK3q1m90JxrEBkJQb0zk/C+D+HAfjiZ7/QE+V1M6seV4JuQDHlOjn+PUcL3gVneKwXjRbkW6NBNpzQ5eM+v5Pjvx+v/Dn+WXl/oOaSu0Gf+OS+goV0t3CyQfQiH8mNKvnb1mndlFy4rSYWo9cJ3NzBvarKjFXF5nGjvDXY13OKlYVxq77ed0t0tSpFc8UN/4Ef0ekeNfhEl1XnUVDnk68w4buNO+QVyIF2Uh8DHB7mSioIGm7y8I+COtTPegmsq+QJgQzwHKE3XI7ToyBC1Q9iaNHJBv6GgTaBxOnLufGowzBPrTBW3HVifOO/XnaqiGFib53bDaJoGoSSZQ==
    DB_USER: AgAXIh5G4k8oCAjIMkWc+zrC25VTte7zzOxH+9/ePrdv+JTHTuJP0qGAFte880Eii2hQaMZ2SbBM0b0tnmu9sj1NSIlBvWBaS9lC6D0N4QSuw6wbv06yN98WFXFHvPK6cy1oyzztq4QcFYjCgbVivOaS8qpGDjKOSPTm3VSQghbfgUEqZQtwXy35qAtAFuNrSUaWQVew7+u7d1k0jx2jG3w5t9+gkJ+eIOa2SwBOdjXbUrEC3uug2bUju7Rqnh6yWkqeQfxcdkuqayky56fup1CisPQorxaiZUHWPGSRRyZjH6sjHFsdCGEPigswcrShJUlm3fnQb3bHSLvV+OQstsUTcUFcd0QntDl8tf9Rl1cROA6ewAfG1Ayg8iMzZzCmmfDtC+yyr0bNLTtGOPKNdK8AKG6/8BKESyd+B/enpKAbk1oY0Dm9ve4ZgTwbkorkZrmp4L/+cRMTVNCmei+5iPwGIqUnW1L//Fftfrrk+kdCI0zcTrRUOve4iumNDHXAUqYTbiRdRVqw+sVBk8yXxjfP5p4CHAn1s77EAD+jas9GxU5nwxBG2m8MUxBrJ1MikgTgfKDLvvNOGBB9GdDIMJbYYqgZNuydNPEbv6Iqr+DkCFF1nOq/Ps+1NyD7hEAYRepjNYvzjvtAMfUJLkJO1BOdX107QUFHohhbrejCd7EomLTsQLpWcA7t24BqmqNtiz39AlSi7kgnTg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: order-projector-db
      namespace: go-ecommerce
    type: Opaque
