---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stripe-secrets
  namespace: go-ecommerce
spec:
  encryptedData:
    STRIPE_SECRET_KEY: AgAzssDg6geH8Fn1Rf/q1mVob4kZf/h4sUtMFTE91KRuWdsUpxFj4rjQVxeuWdXNR2LqJoy0tikJFSXgwigrA8HSnYnbkWX6EWE5t+9KR+x7a5rHk1vMqFZ7wiBUQKY4OyGyqY6MVvb78KpN9pBRjYzt8D61TPsS48pYfrBQI4vJplx0pcqRjOOjsH6HzHnch2Rg7fV0zKtKk3rAPU3F0SAXfc17+n+soWCLM9Qn4zJVUsBGxdHA3GxI6LixlXPg9nVMWTD/2Mo0mj/KirM9wuYg7wf0SHZnRDaSYxXQRa6i9Fo6SQPseQhMs53CpMnqnsCNv29737BOrfqmYxnRjvHdc6oRFvzAaBLLT2iQwmPutHQi9J2QvEix60YGXk59pLZweSralQiVq42N/2/sPbNOXoO/hREzfloXSlsrv7pgKOzJW+hTZUyX0JLzpf2AIZ27wh+MFIkCqHUK/KNqOW6xaDUNDgdk6rEJqRIpV6+jaC7Ck2wEJpW9pOsbLTYIr4HOqrww19OMhYGGLXNWj66k9MvFXj+O4x2LBYdpRwKRWey4zWBnS0LsNioSGerGVrHh8blmEDqNQXtNTBihFL+j/S+GqUr4lQPnve4MSd+jXSH6FEN/rCGUej3hTIncrbm1pRgDMSLK2yWQogpejFjJbXrZoUVRlDPiwa9VbxqizkOUEfv1lSt/Hpbt/sIaEm/A85n8dLPrubPtsk2upQdjtxlcIsVsFgSEmn6sG6RSM31yU2xCc2TjtJm7WIFBvqNH3YpqIO9NQamjwibiCnPgNXTRSb0nPsdPemxWJOEubslm8et7tTqwGTCX0KYhk3F0/dmVbouZvEKeJg==
    STRIPE_WEBHOOK_SECRET: AgDJ6FUU2YjRYkI4cSZCspTDESryInjr/HKwIj2N5Ocdvm9Gi7IFuAQwwp0pB0RHzIcO1vAJ7HpU8y2Z1aNtJRJF2HNr8yX+UDR9LxCXjyCaq2jSmZ+MH8iZbCkVuhPve6yORXeUBpCUPL1JVVGnQB6kn+W22ik4YJ0X2spnO05INFVp0XGJmFzHMcmyzZ/LX7YZaN2Z/nqccXcwnZ2uFVkDRwuAJ4JdtQ6Wi/V2/vL/tyDFNuvB7ZePOfXyU8CY6S2BWTEMAKPglKqnAQKCOm2Tpq0IfmszUhWsrmnRqsQpE/oSmoD0RftKM+G0cU3izMsr+nWqdwJe985u+AN35aiXXMZ93HJi821wfvKQXoqbuOouBWvaOTqI5A6wc3eXAWab6FqmWGtWz1k2bqADSgagpWSgw6FZEZDJAEy8OfhW0btqeC3OnvJ9xOdjMtD3f5oDQLximTHyspqKkdkBSbA9j9X/1ol4MmoylgdMfczJcbgk/DX8gLRMXgFnebw6Kc4VipW9D3A8fjH2MK0I9PkAc7lmYoX1uBuHvzUwJbFOAODiruVZk7MxYOlVCWT46J9Fw4V/YmLo0vDUAxPZ+lTxvgKHmPdF/DiQ6osmXtnNZ7LjueL7tfKKQzT++UvlGhBEof3QRoXLC1ObP4l4LpI8uf2TcS/anMGq2mXYLAKFBoASwrne33Qaia7q1akMllKn2sPQ73QZm+e1X3qfWhzSNcVQ+oDts29pxLMdaSeX0inR8Q9hqw==
  template:
    metadata:
      name: stripe-secrets
      namespace: go-ecommerce
    type: Opaque
