apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grpc-ca
  namespace: go-ecommerce
spec:
  isCA: true
  commonName: grpc-internal-ca
  secretName: grpc-ca-keypair
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
