apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-grpc-tls
  namespace: go-ecommerce
spec:
  commonName: go-auth-service.go-ecommerce.svc.cluster.local
  secretName: auth-grpc-tls
  duration: 720h
  renewBefore: 480h
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - go-auth-service
    - go-auth-service.go-ecommerce
    - go-auth-service.go-ecommerce.svc.cluster.local
  usages:
    - server auth
    - client auth
  issuerRef:
    name: grpc-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: product-grpc-tls
  namespace: go-ecommerce
spec:
  commonName: go-product-service.go-ecommerce.svc.cluster.local
  secretName: product-grpc-tls
  duration: 720h
  renewBefore: 480h
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - go-product-service
    - go-product-service.go-ecommerce
    - go-product-service.go-ecommerce.svc.cluster.local
  usages:
    - server auth
    - client auth
  issuerRef:
    name: grpc-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cart-grpc-tls
  namespace: go-ecommerce
spec:
  commonName: go-cart-service.go-ecommerce.svc.cluster.local
  secretName: cart-grpc-tls
  duration: 720h
  renewBefore: 480h
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - go-cart-service
    - go-cart-service.go-ecommerce
    - go-cart-service.go-ecommerce.svc.cluster.local
  usages:
    - server auth
    - client auth
  issuerRef:
    name: grpc-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: order-grpc-tls
  namespace: go-ecommerce
spec:
  commonName: go-order-service.go-ecommerce.svc.cluster.local
  secretName: order-grpc-tls
  duration: 720h
  renewBefore: 480h
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - go-order-service
    - go-order-service.go-ecommerce
    - go-order-service.go-ecommerce.svc.cluster.local
  usages:
    - client auth
  issuerRef:
    name: grpc-ca-issuer
    kind: Issuer
