apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-ecommerce-ingress
  namespace: go-ecommerce
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/group.name: portfolio
spec:
  ingressClassName: alb
