---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eval-rabbitmq
  namespace: ai-services
spec:
  encryptedData:
    url: AgAHE9UOARuDPc5988lDBdMuj6BFwW3UAkaociMInOVT0XtD9/Il1klKms28umcxyBZi1hLedGxjdkqcz7rV55w2JSwhZ0pwYzv1OjNptFXRgfLXZsywFU4M9FDfq0/VpHK9bgWshcoGASta2vGz+Vfa8wEP0uLHcf5cCz8JZzxOaSikHvtdNeRgPN3obWgnMQxubo4pRiH4lA+6oxXHlY/OtmtWIyyLN+UDc2y2Rvrst2r9jKWvvNEcEIrbKKMgM8xVRuz8mJS/Ny+ffjry6cb7WbydpBxslyXLzrglLF5ITMXYQ1gcQrKf4jBFQK2sjIkv56R0/HjTqh3DHtM0ItsW+fcFhsD8ASsHTN06m9dSivTN25kJYA6xXz17v/BDRCu4KKsZ9yUZoXoyXy2f+M9keo1ExkIL6FOSwqVO3pHDwpdwcEB67WQcu1LaT4ofC1LdQT+Q3gNUDVntL1aSJD1vvUKOWWo23xH5FPTHZ6U5KLQ2oPE3b02ZURWbHIHXC2QiHn0YO9TQyNsBCqRBNR42qp9K7nClSK5EqDFnousJJw+wQvA1LfFLYcSUZlHBhu8PdFsYAMVJBwWZ/hc8lhJticKKaUH+F/ODUtBhMHFLeQZ+05gtpv8Nerb9KgHQOI46rVkQeqP4Rl6jUzlQ2+gYqZxpbealuXY7qVA2HlohDEJNjB2GN1MB+4c2mbv/DRYr5tthHKNFvru1/swFSMRvWuzsAtO9xPmzzUu87lSh9ne51EadvOuwDbSPEgwn6cO2cIziU4Z8vJSXbjO3bQ==
  template:
    metadata:
      name: eval-rabbitmq
      namespace: ai-services
    type: Opaque
