apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-event-exporter-config
  namespace: monitoring
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - type: Warning
          receiver: "loki"
    receivers:
      - name: "loki"
        webhook:
          endpoint: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
          headers:
            Content-Type: "application/json"
          layout:
            streams:
              - stream:
                  job: "kube-event-exporter"
                  namespace: "{{ .InvolvedObject.Namespace }}"
                  reason: "{{ .Reason }}"
                  kind: "{{ .InvolvedObject.Kind }}"
                  name: "{{ .InvolvedObject.Name }}"
                values:
                  - - "{{ .GetTimestampMs }}000000"
                    - "{{ .Reason }}: {{ .Message }} ({{ .InvolvedObject.Kind }}/{{ .InvolvedObject.Name }} in {{ .InvolvedObject.Namespace }})"
