apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: java-tasks
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
