apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: java-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: definitions
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json
            - name: definitions
              mountPath: /etc/rabbitmq/conf.d/20-definitions.conf
              subPath: rabbitmq.conf
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: definitions
          configMap:
            name: rabbitmq-definitions
