---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgB17IAVfNdGFWwYICyASJcVN/Le9KLh1Hlsl5oPAw+/G+1IRYRGigX9JsBpfUQ3AT/sUbIm6ZMMnPzCPURUg0CMdUmqJaHRHkqlM8xbOPauZ2s13U6eJx216kg5JiCpqUZBnsnqN7Uzf4Klyu0XTPkj/JdFMRhCEn1/kWRVxS1i/m5yh9VuV8ACZFIkXwlVG5fZQbdBXJax6PkphsWMw3ebDKRXQ8V6+SP7YWlUxfhByS5poQJs5FPm4gpC6uWGYW4tbT4i3erjdfXpUwTWe0P/nfoGXMUp438XHZSPZIVAebxdMU5fVp7JyHNKw7jaPxF1/zsvCe4GorG0y5MFeZEFxQ+r5HG4+hbGi3xNFjbTlmBnKsbhueCA5asqtQLcJ5HCVRw8Z78RbKqV6/GlYAeGCNWdvP1UBeddqBuaKRwSo/X7LQ34VWUoVpk6SnNR0QHmFFAa2x5gD3vZKcyZbVZMv3rmMFKG3xx8x0g3qzfhGjLUBJaW0Z2k5Ryc5j4Bcc5HqlcW7FSUJtpE6f4f2g9+fCAuxBuqojHQtHx9ewRwH5yue8A+BZrN7eLyOcQ0YKwmR9EeIYjsyKOT/3wTqAFtdxLhfOjeKDpd7ygDK1frdMKlCBSJidQxlDdwIi7foiykyW/QXyDfniRZ3qvfWrZT6MIcTkMEv/5YqF9KjMpxRh7GpxiUOzuKsHuqGyA5OcRaS781dJ3PFmSh0oVYjsJF3H4u/eT92FNUEO0CkjH1IsZ2kfGWBdkpxVPKwC6x
  template:
    metadata:
      name: telegram-bot
      namespace: monitoring
    type: Opaque
