server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:27017/activitydb
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
