apiVersion: v1
kind: Service
metadata:
  name: go-auth-service
  namespace: go-ecommerce
spec:
  selector:
    app: go-auth-service
  ports:
    - name: http
      port: 8091
      targetPort: 8091
    - name: grpc
      port: 9091
      targetPort: 9091
